### ISSUE TITLE
能否添加富文本编辑器类型的表单

### ISSUE THREAD

**Issue by zzdylan** [ichynul/configx#1]
能否添加富文本编辑器类型的表单，比如公告类型的表单

**Comment by ichynul** [comment]
新版本已经支持edito了，做了一些改动，不再以key结尾的标志判断表单类型。
不过使用edito可能会导致value长度超出(55)，你需要修改一些数据库字段。

**Comment by zzdylan** [comment]
好的 非常棒

**Comment by zzdylan** [comment]
现在编辑器默认添加的是ckeditor,我用了社区的wang-editor扩展，如何配合使用呢?

**Comment by ichynul** [comment]
修改了，你更新到最新看看

**Comment by zzdylan** [comment]
可以了，作者辛苦了
