### ISSUE TITLE
无法通过修改admin配置文件来修改配置页的标题和描述。

### ISSUE THREAD

**Issue by sunxiyuan** [ichynul/configx#10]
我做了如下图所示的配置修改并清除了所有缓存，但配置并未生效，也没有任何报错抛出。是我修改标题的方法错了吗？
![TX@9}7F@DY)A% 2C2ZBQ F](https://user-images.githubusercontent.com/35832158/64416539-e9248780-d0c9-11e9-9949-309c7e389be0.png)

**Comment by ichynul** [comment]
标题和描述应该写在翻译文件里面，不是配置里面。

**Comment by sunxiyuan** [comment]
好了，感谢！
