### ISSUE TITLE
"Declaration of Ichynul\RowTable\Field\TextSmall::getPlaceholder() must be compatible with Encore\Admin\Form\Field::getPlaceholder(): string"

### ISSUE THREAD

**Issue by ghost-die** [ichynul/configx#11]
Declaration of Ichynul\RowTable\Field\TextSmall::getPlaceholder() must be compatible with Encore\Admin\Form\Field::getPlaceholder(): string

**Comment by ichynul** [comment]
另外一个扩展的问题，已经修复

**Comment by ghost-die** [comment]
码云上我给你修复了。。你没看PR吧

**Comment by ichynul** [comment]
码云不怎么上，主要是做备份。
