### ISSUE TITLE
不支持 laravel-admin 1.7.8   

### ISSUE THREAD

**Issue by day112** [ichynul/configx#12]
![image](https://user-images.githubusercontent.com/10526728/69506089-0863e000-0f68-11ea-87d1-2b75be26f8c5.png)

**Comment by ichynul** [comment]
这个可以通过你那里修改`composer.json`处理吗？
版本号我也搞不太懂，好像1.2.9 比1.2.14高?
我发布一个新的1.3.0，你试试看。

**Comment by ichynul** [comment]
我现在用的是1.7.9，没问题，应该是其他依赖的问题
