### ISSUE TITLE
str_replace_first()函数未定义

### ISSUE THREAD

**Issue by Cuifc** [ichynul/configx#18]
增加了一个配置项，数字类型，然后报错。

数据库中description 字段值为：
{"__configx_tabs__":{"options":{"base":"\u57fa\u672c\u8bbe\u7f6e","shop":"\u5e97\u94fa\u8bbe\u7f6e","uplaod":"\u4e0a\u4f20\u8bbe\u7f6e","image":"\u56fe\u7247\u8bbe\u7f6e","file":"\u6587\u4ef6\u8bbe\u7f6e"}},"base.order_pay_time":{"options":{"@rules":"required|min:1"},"element":"number","help":"\u8ba2\u5355\u652f\u4ed8\u65f6\u6548\uff0c\u5355\u4f4d\u79d2","name":"\u8ba2\u5355\u652f\u4ed8\u65f6\u6548","order":5}}

再访问页面报如下错误
FatalThrowableError In Tool.php line 51 :
  Call to undefined function Ichynul\Configx\Tools\str_replace_first()

**Comment by ichynul** [comment]
修复了，你更新一下最新版

**Comment by Cuifc** [comment]
> 修复了，你更新一下最新版

太棒了！
