### ISSUE TITLE
如何获取数据？

### ISSUE THREAD

**Issue by Ya-hui** [ichynul/configx#22]
看到有一个issues 但是没看懂 

![image](https://user-images.githubusercontent.com/13138164/78453582-4666d280-76c5-11ea-8fb4-9cf256eb9d0a.png)

数据结构是这样的 config('base.web_site') 获取不到 config('base.web_site_0_0') 也获取不到

**Comment by ichynul** [comment]
你看一下是不是没注册。
<https://github.com/laravel-admin-extensions/config>

Open app/Providers/AppServiceProvider.php, and call the Config::load() method within the boot method:
```php
<?php

namespace App\Providers;

use Encore\Admin\Config\Config;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $table = config('admin.extensions.config.table', 'admin_config');
        if (Schema::hasTable($table)) {
            Config::load();
        }
    }
}
```

**Comment by Ya-hui** [comment]
我在config/admin.php里取不到， 在控制器里能取到 。 配置文件的加载顺序？
