### ISSUE TITLE
配置表单元素为单选框组/是或否/下拉框　读取报错

### ISSUE THREAD

**Issue by sky8652** [ichynul/configx#23]
配置表单元素：选择　[单选框组，是或否  ，下拉框] 　保存后读取列表（admin/configx/edit/0）时报错
 Error In CanCascadeFields.php line 105 :
  Call to a member function fields() on null

**Comment by ichynul** [comment]
修复了，你更新一下看看

**Comment by sky8652** [comment]
OK 可以了，非常感谢，加油

**Comment by phpervip** [comment]
谢谢分享！刚发现这个新的config扩展
