### ISSUE TITLE
ConfigModel.php

### ISSUE THREAD

**Issue by chencongbao** [ichynul/configx#28]
ConfigModel.php 改成 ConfigxModel.php 否则会报错

**Comment by ichynul** [comment]
谢谢，已经修改了。这个问题好奇怪，存在了那么久。

**Comment by TheBlueSkim** [comment]
> 谢谢，已经修改了。这个问题好奇怪，存在了那么久。

好像是composer版本的区别，psr4要求的必须名字和类名一样才可以。
