### ISSUE TITLE
建议配置类型弄成动态

### ISSUE THREAD

**Issue by asundust** [ichynul/configx#3]
建议配置类型弄成动态添加的，config写死的感觉不够灵活。

**Comment by ichynul** [comment]
可以在`app/Admin/bootstrap.php`或`app/Providers/AppServiceProvider.php` 加一句
```php
config(
            [
                'admin.extensions.configx.tabs' => $tabs
            ]
        );
```
`$tabs` 换成你的方式获取的。

我觉得动态也避免不了修改配置文件吧，因为每一个配置键还要有对应的翻译，除非你翻译也可以动态翻译.
