### ISSUE TITLE
Laravel 9 下面有错误

### ISSUE THREAD

**Issue by imnpc** [ichynul/configx#30]
错误代码 Too few arguments to function Ichynul\Configx\Http\Controllers\ConfigxController::edit(), 1 passed in /home/vagrant/Code/base9/vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 54 and exactly 2 expected

Laravel 9  +  laravel-admin 1.8 + PHP 8.1

**Comment by imnpc** [comment]
测试了下 如果菜单设置为 configx/edit/0 是可以访问的  ，默认生成的 configx/edit 是报错的

**Comment by ichynul** [comment]
我修改了一下，默认生成菜单为:`configx/edit/0`
