### ISSUE TITLE
关于图片和文件上传使用的问题

### ISSUE THREAD

**Issue by fsg-herbie** [ichynul/configx#4]
作者你好，关于文件和图片类型的配置上传的文件名使用的是原文件名，有些文件是中文的，而且大小也是原样上传，这样很不友好啊，建议修改
/vendor/ichynul/configx/src/Http/Controllers/ConfigxController.php
第460，474，490，433行增加
$field->move('images/configx')->uniqueName()->crop(1920,1080);
设置文件的路径，使用md5生成文件名，和裁剪图片大小

**Comment by ichynul** [comment]
好的，md5文件名这个可以，但是crop依赖于其他扩展，用户未必有安装此扩展

**Comment by fsg-herbie** [comment]
感谢采纳
