### ISSUE TITLE
无法改变配置项的排序

### ISSUE THREAD

**Issue by sunxiyuan** [ichynul/configx#7]
我尝试用拖动的方式改变排序，但是保存后又变回了原本的排序

**Comment by ichynul** [comment]
保存不是【提交】按钮来控制，拖了后会自动，提示保存成功。

**Comment by sunxiyuan** [comment]
> 保存不是【提交】按钮来控制，拖了后会自动，提示保存成功。

如附件所示，我点击的是右上角的保存，保存后就自动变成了保存前的状态。
![捕获](https://user-images.githubusercontent.com/35832158/62779602-425ac480-bae6-11e9-9d84-7217d4a7d419.PNG)

**Comment by ichynul** [comment]
也跟那个【保存】没关系，拖动结束就会自动保存的，拖一次自动保存一次。至于那个【保存】按钮，是备份用的，就是把当前的这些保存到磁盘。

**Comment by sunxiyuan** [comment]
是configx/src/Http/Controllers/ConfigxController.php文件的postSort方法报错，具体报错的代码如截图所示。报错信息：Call to a member function save() on array。
![捕获](https://user-images.githubusercontent.com/35832158/62815129-8088d000-bb48-11e9-9a04-29235453beb1.PNG)

**Comment by sunxiyuan** [comment]
我用的Laravel版本是5.8，Laravel-admin版本是1.7.3

**Comment by ichynul** [comment]
这个是有问题，我修改了一下，你升级一下新版本

**Comment by sunxiyuan** [comment]
问题已经解决了，感谢！
