### ISSUE TITLE
关于yes_or_no类型字段问题的修复

### ISSUE THREAD

**Issue by zzdylan** [ichynul/configx#8]
当选择yes_or_no类型字段类型的时候，会提示The [yes_or_no] is unuseable!，并且表单的类型没有变成radio而还是text类型，在\vendor\ichynul\configx\src\Tools\Builder.php中修改第395行将
`else if ($type == 'radio_group' ) {
            $type = 'radio';
}`
修改为
`else if ($type == 'radio_group'  ||   $type == 'yes_or_no') {
            $type = 'radio';
}`
问题得到解决，希望作者能在新版本中修复此问题

**Comment by zzdylan** [comment]
另外保存不了值为0的情况

**Comment by ichynul** [comment]
谢谢反馈，已经修复
