### ISSUE TITLE
如何获取数据啊

### ISSUE THREAD

**Issue by chenjiabin** [ichynul/configx#9]
element: table
value:do not delete
Description: json数据

用config($key) 获取到的value是:do not delete

**Comment by ichynul** [comment]
表格，获取数据使用坐标，具体到某行某列。
比如你的key是`base.image`，行列为3x3。
那么获取第一行第一列数据就是：`config('base.image_0_0')`，其它的类似。坐标像数组一样，从0开始。

**Comment by chenjiabin** [comment]
谢谢， 我还以为能直接获取整个table的值。
